plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-neoforge-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

neoForge {
    version = neoforge_version

    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = parchment_minecraft_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

def expandProps = [
        mod_id                  : mod_id,
        mod_name                : mod_name,
        mod_license             : mod_license,
        mod_version             : mod_version,
        mod_authors             : mod_authors,
        mod_description         : mod_description,
        minecraft_version       : minecraft_version,
        minecraft_version_range : minecraft_version_range,
        neoforge_version        : neoforge_version,
        neoforge_version_range  : neoforge_version_range,
        loader_version_range    : loader_version_range
]

tasks.withType(ProcessResources).configureEach {
    inputs.properties expandProps
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand expandProps
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
