org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neoform_version=1.21.1-20240808.144430
neoforge_version=21.1.244
neoforge_version_range=[21.1.0,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=netheroverhaul
mod_name=WT Nether Overhaul
mod_license=MIT
mod_version=1.3.4
mod_group_id=dev.whoteva.netheroverhaul
mod_authors=Whoteva
mod_description=Spawn in a Nether camp, lock the Overworld until a Rift Key, and explore a taller Nether of ravines, biomes, glowstone berries and nether mobs. Pack-ready ore tags for Mekanism, AE2, Immersive Engineering, Create and more.
